# Builds and publishes the Boa Constrictor packages to NuGet.org whenever versions change.
# The NuGet key is currently Andy Knight's NuGet account.
# There are 8-minute sleeps because NuGet needs time to index new packages before they are made available.

name: Publish NuGet packages

on:
  push:
    branches: [main]
      
jobs:
  publish:
    name: Publish
    runs-on: windows-latest
    steps:

      # Prepare the environment

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'


      # Screenplay

      - name: Build Boa.Constrictor.Screenplay project
        run: dotnet build --configuration Release Boa.Constrictor.Screenplay/Boa.Constrictor.Screenplay.csproj

      - name: Pack Boa.Constrictor.Screenplay project
        run: dotnet pack --configuration Release Boa.Constrictor.Screenplay/Boa.Constrictor.Screenplay.csproj --no-build --output Screenplay

      - name: Push Boa.Constrictor.Screenplay package
        run: dotnet nuget push Screenplay/**/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate


      # Selenium and RestSharp

      - name: Wait 8 minutes for NuGet indexing
        run: Start-Sleep -s 480
        shell: powershell

      - name: Build Boa.Constrictor.Selenium project
        run: dotnet build --configuration Release Boa.Constrictor.Selenium/Boa.Constrictor.Selenium.csproj

      - name: Pack Boa.Constrictor.Selenium project
        run: dotnet pack --configuration Release Boa.Constrictor.Selenium/Boa.Constrictor.Selenium.csproj --no-build --output Selenium

      - name: Push Boa.Constrictor.Selenium package
        run: dotnet nuget push Selenium/**/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate

      - name: Build Boa.Constrictor.RestSharp project
        run: dotnet build --configuration Release Boa.Constrictor.RestSharp/Boa.Constrictor.RestSharp.csproj

      - name: Pack Boa.Constrictor.RestSharp project
        run: dotnet pack --configuration Release Boa.Constrictor.RestSharp/Boa.Constrictor.RestSharp.csproj --no-build --output RestSharp

      - name: Push Boa.Constrictor.RestSharp package
        run: dotnet nuget push RestSharp/**/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate


      # Classic

      - name: Wait 8 minutes for NuGet indexing
        run: Start-Sleep -s 480
        shell: powershell

      - name: Build Boa.Constrictor project
        run: dotnet build --configuration Release Boa.Constrictor/Boa.Constrictor.csproj

      - name: Pack Boa.Constrictor project
        run: dotnet pack --configuration Release Boa.Constrictor/Boa.Constrictor.csproj --no-build --output Classic

      - name: Push Boa.Constrictor package
        run: dotnet nuget push Classic/**/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
