# Runs the NUnit unit tests located in the Boa.Constrictor.UnitTests project.
# Warning: Does not run the example tests in the Boa.Constrictor.Example project.

name: Run all unit tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run Screenplay unit tests
        run: dotnet test Boa.Constrictor.Screenplay.UnitTests/Boa.Constrictor.Screenplay.UnitTests.csproj --logger "trx;LogFileName=ScreenplayResults.trx"

      - name: Run Selenium unit tests
        run: dotnet test Boa.Constrictor.Selenium.UnitTests/Boa.Constrictor.Selenium.UnitTests.csproj --logger "trx;LogFileName=SeleniumResults.trx"

      - name: Run RestSharp unit tests
        run: dotnet test Boa.Constrictor.RestSharp.UnitTests/Boa.Constrictor.RestSharp.UnitTests.csproj --logger "trx;LogFileName=RestSharpResults.trx"

      - name: Archive Screenplay unit test results
        uses: actions/upload-artifact@v3
        with:
          name: Screenplay unit test results
          path: Boa.Constrictor.Screenplay.UnitTests/TestResults/ScreenplayResults.trx
          retention-days: 30

      - name: Archive Selenium unit test results
        uses: actions/upload-artifact@v3
        with:
          name: Selenium unit test results
          path: Boa.Constrictor.Selenium.UnitTests/TestResults/SeleniumResults.trx
          retention-days: 30

      - name: Archive RestSharp unit test results
        uses: actions/upload-artifact@v3
        with:
          name: RestSharp unit test results
          path: Boa.Constrictor.RestSharp.UnitTests/TestResults/RestSharpResults.trx
          retention-days: 30
